### ISSUE TITLE
big scam

### ISSUE THREAD

**Issue by TadaDeveloper** [AnarchyDevTeam/Projects#3]
i was casually watching porn and out of nowhere it said i haxxed u

**Comment by Ovrete** [comment]
good for u... y did u start this just to be a bitch and lie? like fuck u lmao

**Comment by TadaDeveloper** [comment]
> good for u... y did u start this just to be a bitch and lie? like fuck u lmao

tada man bad!111

**Comment by eska68** [comment]
bruh stfu xD

**Comment by iLinked1337** [comment]
ok
