### ISSUE TITLE
iLinked Github Termed

### ISSUE THREAD

**Issue by zihasz** [AnarchyDevTeam/Projects#7]
sad github stupid faggot

**Comment by LeetCseto** [comment]
nigger

Den søn. 4. okt. 2020 kl. 20.03 skrev zihasz <notifications@github.com>:

**Comment by zihasz** [comment]
lmao

**Comment by TheOPtimal** [comment]
I suggest either selfhosting a GitLab or Gitea instance or moving over to a public instance such as CodeBerg, GitLab.com, FramaGit or another.

**Comment by TheOPtimal** [comment]
I suggest either selfhosting a GitLab or Gitea instance or moving over to a public instance such as CodeBerg, GitLab.com, FramaGit or another.
